name: Format Codes

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
  workflow_dispatch:

jobs:
  Format_Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.x"

      - name: Install Formatting Tools
        run: |
             pip install --upgrade pip
             pip install autoflake isort black pyupgrade pylint

      - name: format codes
        run: |
          autoflake --in-place --recursive .

          black .
          isort .


      - name: Update Syntax to python3.10+
        run: |
          find . -name "*.py" -exec pyupgrade --py39-plus {} \;

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format Codes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@v1.0.1