name: Replace
on:
  push:
    paths:
      - ".github/workflows/replace.yml"
jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Replace text
        shell: bash
        run: |
          declare -A replacements=(
            ["USER_IDENTIFIER_REQUIRED"]="general_1"
            ["COMMAND_USAGE_ERROR"]="general_2"
            ["ERROR_OCCURRED_MSG"]="general_3"
            ["ANONYMOUS_ADMIN"]="general_4"
            ["PERMISSION_REQUIRED"]="general_5"
            ["NO_ACTIVE_VIDEO_STREAM"]="general_6"

            ["OVERLOAD_WAIT_MSG"]="tg_1"
            ["DOWNLOAD_FAILED_MSG"]="tg_2"

            ["BOT_ADMIN_REQUIRED"]="call_1"
            ["ASSISTANT_BANNED"]="call_2"
            ["ASSISTANT_INVITE_EXCEPTION"]="call_3"
            ["INVITE_PERMISSION_REQUIRED"]="call_4"
            ["ASSISTANT_JOINING_WAIT"]="call_5"
            ["ASSISTANT_JOIN_SUCCESS"]="call_6"
            ["STREAM_SWITCH_FAILED"]="call_7"
            ["DOWNLOADING_NEXT_TRACK"]="call_8"
            ["ASSISTANT_TOO_MANY_CHATS"]="call_9"
            ["ASSISTANT_FLOOD_WAIT"]="call_10"

            ["MAX_AUTHORIZED_USERS"]="auth_1"
            ["AUTHORIZED_USER_ADDED"]="auth_2"
            ["USER_ALREADY_AUTHORIZED"]="auth_3"
            ["AUTHORIZED_USER_REMOVED"]="auth_4"
            ["USER_NOT_AUTHORIZED"]="auth_5"
            ["FETCHING_AUTHORIZED_USERS"]="auth_6"
            ["AUTHORIZED_USERS_LIST"]="auth_7"
            ["AUTHORIZED_BY"]="auth_8"
          
          )

          for key in "${!replacements[@]}"; do
            find . -type d \( -name ".git" -o -path "./.github/*" \) -prune -o \
            \( -type f \( -name "*.py" -o -name "*.yml" \) \) \
            -exec sed -i "s/\b$key\b/${replacements[$key]}/g" {} +
          done

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Replace"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@dev