name: Update uv Cache

on:
  push:
    paths:
      - "**.toml"
  workflow_dispatch:

jobs:
  update:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.x"

      - name: Update uv.lock
        run: |
          pip install --upgrade uv
          uv lock
          uv sync

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(deps): update uv.lock file"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - uses: Mattraks/delete-workflow-runs@v2
        with:
          delete_workflow_pattern: "Format Codes"
          keep_minimum_runs: 0
          retain_days: 0
